import { motion } from "framer-motion";
import logo from "@/assets/logobanana.jpg";

export function About() {
  return (
    <section id="about" className="relative py-24 px-4">
      <div className="container mx-auto grid md:grid-cols-2 gap-12 items-center max-w-6xl">
        <motion.div
          initial={{ opacity: 0, rotate: -10 }}
          whileInView={{ opacity: 1, rotate: -3 }}
          viewport={{ once: true }}
          className="relative"
        >
          <div className="absolute -inset-4 bg-gradient-to-tr from-banana to-neon-green blur-2xl opacity-50" />
          <img src={logo} alt="James Banana" className="relative w-full max-w-sm mx-auto rounded-3xl border-4 border-foreground/10" />
        </motion.div>
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="space-y-5"
        >
          <p className="text-sm font-black uppercase tracking-[0.3em] text-neon-green">Origin Story</p>
          <h2 className="text-5xl md:text-6xl font-black">
            Who Is <span className="text-banana-gradient">James Banana?</span>
          </h2>
          <p className="text-lg text-muted-foreground">
            Nobody knows where James Banana came from. Some say he was a cat who got trapped inside a banana. Others believe he was generated by an AI experiment that escaped into the internet.
          </p>
          <p className="text-lg text-muted-foreground">
            Whatever the truth may be, James Banana has become a symbol of creativity, humor, and internet chaos. Built for creators, meme lovers, and degens alike — he gives everyone the power to turn simple ideas into viral AI-generated video content.
          </p>
          <p className="text-xl font-black text-banana">
            No tools. No experience. No limits. Just memes, imagination, and pure banana energy. 🍌
          </p>
        </motion.div>
      </div>
    </section>
  );
}